//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDepartmentAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResultDetail
    {
        public string Name { get; set; }
        public string DepartmentFullName { get; set; }
        public string StudentId { get; set; }
        public string YearTermName { get; set; }
        public Nullable<double> TotalCompletedCredit { get; set; }
        public Nullable<double> TotalGpa { get; set; }
        public Nullable<double> Cgpa { get; set; }
    }
}
